/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proj_filetransfer;

import javafx.scene.paint.Color;
import javax.swing.BorderFactory;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;

/**
 *
 * @author Poras
 */
public class HistoryOfTransfersScreen extends javax.swing.JPanel {

    /**
     * Creates new form HistoryOfTransfersScreen
     */
    public HistoryOfTransfersScreen() {
        initComponents();
        this.setBounds( 0, 0, 640, 360);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(6, 231, 236));
        setMaximumSize(new java.awt.Dimension(640, 360));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setLayout(null);

        jList1.setBackground(new java.awt.Color(0, 0, 0));
        jList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jList1.setFont(new java.awt.Font("Transformers Movie", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(6, 231, 236));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Image1", "Audio1", "Video1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setSelectionBackground(new java.awt.Color(6, 231, 236));
        jList1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2);
        jScrollPane2.setBounds(30, 100, 580, 170);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Transformers Movie", 0, 22)); // NOI18N
        jTable1.setForeground(new java.awt.Color(6, 231, 236));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"You", "Umang-PC", "Image1", "E:\\", "22456"}
                },
                new String [] {
                    "Sender", "Receiver", "Filename", "Location", "FileSize(KB)"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jTable1.setGridColor(new java.awt.Color(6, 231, 236));
            jTable1.setInheritsPopupMenu(true);
            jTable1.setMaximumSize(new java.awt.Dimension(300, 64));
            jTable1.setMinimumSize(new java.awt.Dimension(300, 64));
            jTable1.setRowHeight(26);
            jTable1.setSelectionBackground(new java.awt.Color(6, 231, 236));
            jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
            jScrollPane1.setViewportView(jTable1);

            add(jScrollPane1);
            jScrollPane1.setBounds(30, 280, 580, 50);

            jButton4.setBackground(new java.awt.Color(0, 0, 0));
            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj_filetransfer/delete.png"))); // NOI18N
            jButton4.setBorderPainted(false);
            jButton4.setContentAreaFilled(false);
            add(jButton4);
            jButton4.setBounds(570, 60, 50, 30);

            jButton3.setBackground(new java.awt.Color(0, 0, 0));
            jButton3.setFont(new java.awt.Font("Transformers Movie", 0, 24)); // NOI18N
            jButton3.setForeground(new java.awt.Color(6, 231, 236));
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj_filetransfer/back.png"))); // NOI18N
            jButton3.setBorderPainted(false);
            jButton3.setContentAreaFilled(false);
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            add(jButton3);
            jButton3.setBounds(0, 50, 90, 50);

            jLabel1.setBackground(new java.awt.Color(0, 0, 0));
            jLabel1.setFont(new java.awt.Font("Transformers Movie", 0, 44)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(6, 231, 236));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Transfer History");
            jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            add(jLabel1);
            jLabel1.setBounds(110, 60, 440, 40);

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj_filetransfer/allPageHeader.png"))); // NOI18N
            add(jLabel2);
            jLabel2.setBounds(130, 0, 370, 40);

            jButton2.setBackground(new java.awt.Color(0, 0, 0));
            jButton2.setFont(new java.awt.Font("Transformers Movie", 0, 24)); // NOI18N
            jButton2.setForeground(new java.awt.Color(6, 231, 236));
            jButton2.setText("X");
            jButton2.setBorderPainted(false);
            jButton2.setContentAreaFilled(false);
            jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton2MouseClicked(evt);
                }
            });
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            add(jButton2);
            jButton2.setBounds(595, 0, 45, 40);

            jButton1.setBackground(new java.awt.Color(0, 0, 0));
            jButton1.setFont(new java.awt.Font("Transformers Movie", 0, 18)); // NOI18N
            jButton1.setForeground(new java.awt.Color(6, 231, 236));
            jButton1.setText("_");
            jButton1.setBorderPainted(false);
            jButton1.setContentAreaFilled(false);
            jButton1.setMaximumSize(new java.awt.Dimension(45, 29));
            jButton1.setMinimumSize(new java.awt.Dimension(45, 29));
            jButton1.setPreferredSize(new java.awt.Dimension(45, 29));
            jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            add(jButton1);
            jButton1.setBounds(550, 0, 45, 30);
        }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
